language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer install --prefer-source --no-interaction --dev
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls
