<?php

namespace FL\QBJSParser\Tests\Parser\Doctrine;

use FL\QBJSParser\Parser\Doctrine\StringManipulator;

class StringManipulatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @test
     */
    public function testReplaceAllDotsExceptLastTwo()
    {
        $this->assertEquals(
            'object_something.cool.today',
            StringManipulator::replaceAllDotsExceptLastTwo('object.something.cool.today')
        );
        $this->assertEquals(
            'object_something.cool.',
            StringManipulator::replaceAllDotsExceptLastTwo('object.something.cool.')
        );
        $this->assertEquals(
            'object.something.cool',
            StringManipulator::replaceAllDotsExceptLastTwo('object.something.cool')
        );
        $this->assertEquals(
            'object.something.',
            StringManipulator::replaceAllDotsExceptLastTwo('object.something.')
        );
        $this->assertEquals(
            'object.something',
            StringManipulator::replaceAllDotsExceptLastTwo('object.something')
        );
        $this->assertEquals(
            'object.',
            StringManipulator::replaceAllDotsExceptLastTwo('object.')
        );
        $this->assertEquals(
            'object',
            StringManipulator::replaceAllDotsExceptLastTwo('object')
        );
        $this->assertEquals(
            '_object_something.cool.today',
            StringManipulator::replaceAllDotsExceptLastTwo('.object.something.cool.today')
        );
        $this->assertEquals(
            '_object_something.cool.',
            StringManipulator::replaceAllDotsExceptLastTwo('.object.something.cool.')
        );
        $this->assertEquals(
            '_object.something.cool',
            StringManipulator::replaceAllDotsExceptLastTwo('.object.something.cool')
        );
        $this->assertEquals(
            '_object.something.',
            StringManipulator::replaceAllDotsExceptLastTwo('.object.something.')
        );
        $this->assertEquals(
            '.object.something',
            StringManipulator::replaceAllDotsExceptLastTwo('.object.something')
        );
        $this->assertEquals(
            '.object.',
            StringManipulator::replaceAllDotsExceptLastTwo('.object.')
        );
        $this->assertEquals(
            '.object',
            StringManipulator::replaceAllDotsExceptLastTwo('.object')
        );
        $this->assertEquals(
            '.',
            StringManipulator::replaceAllDotsExceptLastTwo('.')
        );
    }
    /**
     * @test
     */
    public function testReplaceAllDotsExceptLast()
    {
        $this->assertEquals(
            'object_something_cool.today',
            StringManipulator::replaceAllDotsExceptLast('object.something.cool.today')
        );
        $this->assertEquals(
            'object_something_cool.',
            StringManipulator::replaceAllDotsExceptLast('object.something.cool.')
        );
        $this->assertEquals(
            'object_something.cool',
            StringManipulator::replaceAllDotsExceptLast('object.something.cool')
        );
        $this->assertEquals(
            'object_something.',
            StringManipulator::replaceAllDotsExceptLast('object.something.')
        );
        $this->assertEquals(
            'object.something',
            StringManipulator::replaceAllDotsExceptLast('object.something')
        );
        $this->assertEquals(
            'object.',
            StringManipulator::replaceAllDotsExceptLast('object.')
        );
        $this->assertEquals(
            'object',
            StringManipulator::replaceAllDotsExceptLast('object')
        );
        $this->assertEquals(
            '_object_something_cool.today',
            StringManipulator::replaceAllDotsExceptLast('.object.something.cool.today')
        );
        $this->assertEquals(
            '_object_something_cool.',
            StringManipulator::replaceAllDotsExceptLast('.object.something.cool.')
        );
        $this->assertEquals(
            '_object_something.cool',
            StringManipulator::replaceAllDotsExceptLast('.object.something.cool')
        );
        $this->assertEquals(
            '_object_something.',
            StringManipulator::replaceAllDotsExceptLast('.object.something.')
        );
        $this->assertEquals(
            '_object.something',
            StringManipulator::replaceAllDotsExceptLast('.object.something')
        );
        $this->assertEquals(
            '_object.',
            StringManipulator::replaceAllDotsExceptLast('.object.')
        );
        $this->assertEquals(
            '.object',
            StringManipulator::replaceAllDotsExceptLast('.object')
        );
        $this->assertEquals(
            '.',
            StringManipulator::replaceAllDotsExceptLast('.')
        );
    }

    /**
     * @test
     */
    public function testReplaceAllDots()
    {
        $this->assertEquals(
            'object_something_cool_today',
            StringManipulator::replaceAllDots('object.something.cool.today')
        );
        $this->assertEquals(
            'object_something_cool_',
            StringManipulator::replaceAllDots('object.something.cool.')
        );
        $this->assertEquals(
            'object_something_cool',
            StringManipulator::replaceAllDots('object.something.cool')
        );
        $this->assertEquals(
            'object_something_',
            StringManipulator::replaceAllDots('object.something.')
        );
        $this->assertEquals(
            'object_something',
            StringManipulator::replaceAllDots('object.something')
        );
        $this->assertEquals(
            'object_',
            StringManipulator::replaceAllDots('object.')
        );
        $this->assertEquals(
            'object',
            StringManipulator::replaceAllDots('object')
        );
        $this->assertEquals(
            '_object_something_cool_today',
            StringManipulator::replaceAllDots('.object.something.cool.today')
        );
        $this->assertEquals(
            '_object_something_cool_',
            StringManipulator::replaceAllDots('.object.something.cool.')
        );
        $this->assertEquals(
            '_object_something_cool',
            StringManipulator::replaceAllDots('.object.something.cool')
        );
        $this->assertEquals(
            '_object_something_',
            StringManipulator::replaceAllDots('.object.something.')
        );
        $this->assertEquals(
            '_object_something',
            StringManipulator::replaceAllDots('.object.something')
        );
        $this->assertEquals(
            '_object_',
            StringManipulator::replaceAllDots('.object.')
        );
        $this->assertEquals(
            '_object',
            StringManipulator::replaceAllDots('.object')
        );
        $this->assertEquals(
            '_',
            StringManipulator::replaceAllDots('.')
        );
    }
}
